# #############################################################################
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################
---

centralidp:
  enabled: true
  keycloak:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: "centralidp.tx.test"
      annotations:
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-origin: "http://centralidp.tx.test"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
        nginx.ingress.kubernetes.io/proxy-buffering: "on"
        nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
        nginx.ingress.kubernetes.io/use-regex: "true"
      tls: false
    # -- uncomment the following for persistence
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true


bdrs-server-memory:
  enabled: true
  seeding:
    bpnList:
      - bpn: "BPNL000000000000"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL000000000000"
      - bpn: "BPNL00000003B3NX"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003B3NX"
      - bpn: "BPNL00000003CSGV"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003CSGV"
      - bpn: "BPNL00000003B6LU"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003B6LU"
      - bpn: "BPNL00000003AXS3"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003AXS3"
      - bpn: "BPNL00000003AZQP"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003AZQP"
      - bpn: "BPNL00000003AWSS"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003AWSS"
      - bpn: "BPNL00000003AYRE"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003AYRE"
      - bpn: "BPNL00000003AVTH"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003AVTH"
      - bpn: "BPNL00000000BJTL"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000000BJTL"
      - bpn: "BPNL00000003CML1"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003CML1"
      - bpn: "BPNL00000003B2OM"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003B2OM"
      - bpn: "BPNL00000003B0Q0"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003B0Q0"
      - bpn: "BPNL00000003B5MJ"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003B5MJ"
      - bpn: "BPNS0000000008ZZ"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNS0000000008ZZ"
      - bpn: "BPNL00000003CNKC"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003CNKC"
      - bpn: "BPNS00000008BDFH"
        did: "did:web:ssi-dim-wallet-stub.tx.test:BPNS00000008BDFH"
  hostname: &hostname bdrs-server.tx.test
  server:
    trustedIssuers:
      - did:web:ssi-dim-wallet-stub.tx.test:BPNL000000000000
    ingresses:
      - enabled: true
        hostname: *hostname
        endpoints:
          - directory
          - management
        tls:
          enabled: false

dataconsumerOne:
  enabled: true
  secrets:
    edc-miw-keycloak-secret: BPNL00000003AZQP
  tractusx-connector:
    participant:
      id: BPNL00000003AZQP
    iatp:
      id: did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003AZQP
      trustedIssuers:
        - did:web:ssi-dim-wallet-stub.tx.test:BPNL000000000000
      sts:
        dim:
          url: http://ssi-dim-wallet-stub.tx.test/api/sts
        oauth:
          token_url: http://ssi-dim-wallet-stub.tx.test/oauth/token
          client:
            id: BPNL00000003AZQP
            secret_alias: edc-miw-keycloak-secret
    controlplane:
      env:
        TX_IAM_IATP_CREDENTIALSERVICE_URL: http://ssi-dim-wallet-stub.tx.test/api
    dataplane:
      env:
        TX_IAM_IATP_CREDENTIALSERVICE_URL: http://ssi-dim-wallet-stub.tx.test/api
    # -- uncomment the following for persistence
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true

tx-data-provider:
  seedTestdata: true
  enabled: true
  secrets:
    edc-miw-keycloak-secret: BPNL00000003AYRE
  tractusx-connector:
    participant:
      id: BPNL00000003AYRE
    iatp:
      id: did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003AYRE
      trustedIssuers:
        - did:web:ssi-dim-wallet-stub.tx.test:BPNL000000000000
      sts:
        dim:
          url: http://ssi-dim-wallet-stub.tx.test/api/sts
        oauth:
          token_url: http://ssi-dim-wallet-stub.tx.test/oauth/token
          client:
            id: BPNL00000003AYRE
            secret_alias: edc-miw-keycloak-secret
    controlplane:
      env:
        TX_IAM_IATP_CREDENTIALSERVICE_URL: http://ssi-dim-wallet-stub.tx.test/api
    dataplane:
      env:
        TX_IAM_IATP_CREDENTIALSERVICE_URL: http://ssi-dim-wallet-stub.tx.test/api
  # -- uncomment the following for persistence
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true
  # digital-twin-registry:
  #   postgresql:
  #     primary:
  #       persistence:
  #         enabled: true

dataconsumerTwo:
  enabled: false
  secrets:
    edc-miw-keycloak-secret: BPNL000000000000
  tractusx-connector:
    participant:
      id: BPNL00000003AVTH
    iatp:
      id: did:web:ssi-dim-wallet-stub.tx.test:BPNL00000003AVTH
      trustedIssuers:
        - did:web:ssi-dim-wallet-stub.tx.test:BPNL000000000000
      sts:
        dim:
          url: http://ssi-dim-wallet-stub.tx.test/api/sts
        oauth:
          token_url: http://ssi-dim-wallet-stub.tx.test/oauth/token
          client:
            id: BPNL000000000000
            secret_alias: edc-miw-keycloak-secret
    controlplane:
      env:
        TX_IAM_IATP_CREDENTIALSERVICE_URL: http://ssi-dim-wallet-stub.tx.test/api
    dataplane:
      env:
        TX_IAM_IATP_CREDENTIALSERVICE_URL: http://ssi-dim-wallet-stub.tx.test/api
    # -- uncomment the following for persistence
    # postgresql:
    #   primary:
    #     persistence:
    #       enabled: true

pgadmin4:
  enabled: true
  # -- uncomment the following for persistence
  # persistentVolume:
  #   enabled: true

ssi-credential-issuer:
  enabled: true
  walletAddress: "http://ssi-dim-wallet-stub.tx.test"
  walletTokenAddress: "http://ssi-dim-wallet-stub.tx.test/oauth/token"
  issuer:
    credential:
      issuerDid: "did:web:ssi-dim-wallet-stub.tx.test:BPNL000000000000"
      issuerBpn: "BPNL000000000000"
      statusListUrl: "http://ssi-dim-wallet-stub.tx.test/status-list/BPNL000000000000/8a6c7486-1e1f-4555-bdd2-1a178182651e"

ssi-dim-wallet-stub:
  enabled: true
