# #############################################################################
  # Copyright (c) 2025 Contributors to the Eclipse Foundation
  #
  # See the NOTICE file(s) distributed with this work for additional
  # information regarding copyright ownership.
  #
  # This program and the accompanying materials are made available under the
  # terms of the Apache License, Version 2.0 which is available at
  # https://www.apache.org/licenses/LICENSE-2.0.
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  # WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  # License for the specific language governing permissions and limitations
  # under the License.
  #
  # SPDX-License-Identifier: Apache-2.0
  # #############################################################################
{{- if and (index .Values "tls-issuer") (index .Values "tls-issuer" "acme" "enabled")}}
# See https://cert-manager.io/docs/configuration/acme/
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: umbrella-ca-issuer
  {{- if index .Values "cert-manager" "enabled" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,post-delete
    "helm.sh/hook-weight": "0"
  {{ end }}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ index .Values "tls-issuer" "acme" "email" }}
    # If the ACME server supports profiles, you can specify the profile name here.
    # See #acme-certificate-profiles below.
    profile: {{ index .Values "tls-issuer" "acme" "profile" | default "tlsserver" }}
    server: {{ index .Values "tls-issuer" "acme" "server" | default "https://acme-v02.api.letsencrypt.org/directory" }}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      # This is your identity with your ACME provider. Any secret name may be
      # chosen. It will be populated with data automatically, so generally
      # nothing further needs to be done with the secret. If you lose this
      # identity/secret, you will be able to generate a new one and generate
      # certificates for any/all domains managed using your previous account,
      # but you will be unable to revoke any certificates generated using that
      # previous account.
      name: {{ index .Values "tls-issuer" "acme" "privateKeySecretRef" | default "umbrella-issuer-account-key" }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ index .Values "tls-issuer" "acme" "ingressClassName" | default "nginx" }}
{{ end }}
