{{- if and (index .Values "external-secrets" "enabled") (index .Values "externalSecrets") }}
{{- range $secretName, $kv := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
{{- range $key, $_ := $kv }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ printf "%s-%s" $secretName $key }}
{{- end }}
---
{{- end }}
{{- end }}
