{{- if and (index .Values "external-secrets" "enabled") (not .Values.vault.enabled) .Values.externalSecrets }}
{{- range $secretName, $kv := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
{{- range $key, $_ := $kv }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ printf "%s-%s" $secretName $key }}
{{- end }}
---
{{- end }}
{{- end }}
