{{- if (index .Values "external-secrets" "enabled") }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake-store
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    fake:
      data:
{{- range $secretName, $kv := .Values.externalSecrets }}
{{- range $key, $val := $kv }}
        - key: {{ printf "%s-%s" $secretName $key }}
{{- if (kindIs "string" $val) }}
          value: {{ $val | quote }}
{{- else }}
          value: |-
{{-   range $line := regexSplit "\n" ($val | toString) -1 }}
            {{ $line }}
{{-   end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
