{{ if index .Values "smtp4dev" "enabled" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smtp4dev-ingress
  labels:
    name: smtp4dev-ingress
spec:
  rules:
  - host: {{ .Values.smtp4dev.ingress.url }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: smtp4dev
            port: 
              number: {{ .Values.smtp4dev.ports.http }}
{{ end }}
