{{- if (index .Values "external-secrets" "enabled") }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secretstore
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "9"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  provider:
    vault:
      server: http://vault.default.svc.cluster.local:8200
      path: test
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: aHZzLmVOS29Eckdwd09MQzM1VGFYOHNWVE9wNQ==
{{- end }}