{{- if (index .Values "external-secrets" "enabled") }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-external-secret
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: example-secret
  data:
    - secretKey: username
      remoteRef:
        key: username
    - secretKey: password
      remoteRef:
        key: password
{{- end }}