{{- if (index .Values "external-secrets" "enabled") }}
apiVersion: v1
kind: Pod
metadata:
  name: test-external-secret
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app: test-external-secret
spec:
  containers:
  - name: test-container
    image: busybox:latest
    command: ['sh', '-c', 'echo "Testing external secret access" && echo "Secret value: $SECRET_VALUE" && echo "Test completed successfully"']
    env:
    - name: SECRET_VALUE
      valueFrom:
        secretKeyRef:
          name: example-secret
          key: password
  restartPolicy: Never
{{- end }}